/**
 * Firestore data model references and converters.
 *
 * Collections:
 * - users
 *   - id: Firebase Authentication UID
 *   - displayName: string
 *   - email: string
 *   - role: "student" | "staff" | "admin"
 *   - department: string | null
 *   - createdAt: Timestamp
 *   - updatedAt: Timestamp
 *
 * - grievances
 *   - id: auto-id generated by Firestore (also used as grievanceId)
 *   - grievanceNumber: string (e.g. "GRV-2025-0001")
 *   - createdBy: string (user UID) | null for anonymous submissions
 *   - category: "Academic" | "Hostel" | "Facilities" | "Administration" | "Other"
 *   - title: string
 *   - description: string
 *   - attachments: Array<{ fileName: string, fileUrl: string, fileType: string }>
 *   - status: "submitted" | "in_review" | "in_progress" | "resolved" | "rejected"
 *   - assignedTo: string | null (committee/department identifier)
 *   - history: Array<{
 *       status: string,
 *       comment: string,
 *       updatedBy: string,
 *       updatedAt: Timestamp,
 *     }>
 *   - anonymous: boolean
 *   - resolutionFeedback: {
 *       rating: number (1-5),
 *       comment: string,
 *       submittedAt: Timestamp,
 *     } | null
 *   - escalationLevel: number (0 base)
 *   - createdAt: Timestamp
 *   - updatedAt: Timestamp
 *
 * - notifications
 *   - id: auto-id
 *   - grievanceId: string
 *   - recipientId: string
 *   - message: string
 *   - read: boolean
 *   - createdAt: Timestamp
 *
 * - analyticsSnapshots
 *   - id: ISO date string
 *   - data: {
 *       totalGrievances: number,
 *       resolvedCount: number,
 *       avgResolutionTimeHours: number,
 *       byCategory: Record<string, number>,
 *       openByStage: Record<string, number>,
 *     }
 */

export const GRIEVANCE_STATUSES = [
  "submitted",
  "in_review",
  "in_progress",
  "resolved",
  "rejected",
];

export const GRIEVANCE_CATEGORIES = [
  "Academic",
  "Hostel",
  "Facilities",
  "Administration",
  "Other",
];

export const USER_ROLES = ["student", "staff", "admin"];
